### ISSUE TITLE
Support for newer kernels?

### ISSUE THREAD

**Issue by aubade** [reporter123/hfsplusdkms#5]
The kernels in Ubuntu Trusty and Utopic (3.14 and 3.16 respectively) are too new for this driver, it seems. It doesn't want to compile on either. Is there any chance we could get this updated?

**Comment by reporter123** [comment]
3.14 support is now up

**Comment by snshn** [comment]
Support for 3.16.x-3.19.x has been added to my fork, please feel free to pull and test it (remember to back-up your data before using it) ( https://github.com/defiant-labs/hfsplusdkms )

**Comment by reporter123** [comment]
This should be working for 3.16 - 3.18.
